### ISSUE TITLE
Could you please share the required nx files again? 

### ISSUE THREAD

**Issue by huafengguo** [ryantpayton/MapleStory-Client#13]
Could you please share the required nx files again? I searched the Internet and couldn't find the correct one. Thank you. @ryantpayton

**Comment by venufix** [comment]
@huafengguo Add me on discord lets handle this client together I think this repo is abandoned

**Comment by ryantpayton** [comment]
I can reshare them, give me about a week I can re-test the code and get latest source code up and working and reupload all the files needed. @huafengguo

**Comment by huafengguo** [comment]
I'm looking forward to it, and thank you in advance. @ryantpayton

**Comment by venufix** [comment]
Thank you very much, once the setup is working we actually will be able to contribute to the client @ryantpayton

**Comment by ryantpayton** [comment]
@venufix Working on it as we speak. I follow the `README`s in both projects to always setup from a fresh environment. That always gets me to where I need to be. The missing files seem to be the standstill for most people. Converting WZ files should also be without issue but I understand most people have issues and don't have v228.3 which is what the latest build is on right now. So I am getting downloads prepared.

**Comment by ryantpayton** [comment]
@venufix @huafengguo Update, I got all files finished, I will begin testing tomorrow and if all goes well I will upload all files and check in the changes to the README so you can get the links.

**Comment by ryantpayton** [comment]
@venufix @huafengguo
![image](https://github.com/ryantpayton/MapleStory-Client/assets/48335966/4717f373-fd50-4f92-a6ff-4735b89b5816)
![image](https://github.com/ryantpayton/MapleStory-Client/assets/48335966/bd4fc456-0a84-4d36-9d38-28dc5bbf9210)
I will upload files soon, they will take a while to upload them all.

This is using v228.3 clean WZ files converted to NX btw.
XML dumped from WZ as well.

Client-Server all match v228.3 which is latest source code.

**Comment by ryantpayton** [comment]
Latest files for the client can be downloaded through the [README.md](https://github.com/ryantpayton/MapleStory-Client/blob/master/README.md)
Extracted XML files for the server can be downloaded through the [README.md](https://github.com/ryantpayton/MapleStory-Server/blob/master/README.md) as well

This should be everything someone needs to:

1. Download a working localhost to use with the server
2. Have the converted NX files to be used with the client
3. Have the extracted XML files to be used with the server

Please let me know if you guys need anything else.

**Comment by venufix** [comment]
Thank you very much!!
Can you explain to me how come the client using wz files of v228.3 while the server is supporting only v83? @ryantpayton 
Or do you use other server than heavenMS?

**Comment by ryantpayton** [comment]
@venufix I use my own server based on HeavenMS that supports the higher WZ files. Located [here](https://github.com/ryantpayton/MapleStory-Server).

**Comment by huafengguo** [comment]
@ryantpayton 
I used your shared nx file and your server and the game ran. However, there are several obvious problems. 
1. The monsters neither move nor attack. The snail simply stood still, and the mushroom blinked but did not move. 
2. Talk to an NPC and click the OK button to end the conversation. Clicking any NPC again will no longer open the dialog box, and the server command line only outputs NPC_TALK. 
3. Most NPCs in the birthplace do not have scripts, and the game flow is basically impossible to progress. 
Is your local computer running correctly?
![怪物站着不动](https://github.com/ryantpayton/MapleStory-Client/assets/40561844/5036a2e1-be85-4983-bd8c-7646bceb4a07)
![说了一次话之后再点就没有了反应，命令行一直输出NPC_TALK](https://github.com/ryantpayton/MapleStory-Client/assets/40561844/fa11f282-e715-4afc-bab1-dcee14265b4e)

**Comment by ryantpayton** [comment]
@huafengguo Yes this is all known bugs, your client seems to be in the same state mine is in.

**Comment by speedyHKjournalist** [comment]
Let's implement npc talk and quest opcodes together as I've already seen some self-made Unity MapleStory client with quest and npc-talk available.

**Comment by huafengguo** [comment]
@speedyHKjournalist 在B站看到的？

**Comment by speedyHKjournalist** [comment]
> @speedyHKjournalist 在B站看到的？

Yes

**Comment by ryantpayton** [comment]
> Let's implement npc talk and quest opcodes together as I've already seen some self-made Unity MapleStory client with quest and npc-talk available.

Yeah absolutely. You can feel free to send a pull request or tell me what needs done and I can implement it for you.

**Comment by speedyHKjournalist** [comment]
> > Let's implement npc talk and quest opcodes together as I've already seen some self-made Unity MapleStory client with quest and npc-talk available.
> 
> Yeah absolutely. You can feel free to send a pull request or tell me what needs done and I can implement it for you.


![](https://i.stack.imgur.com/0n8HP.jpg)
I managed to migrate the linux branch to android using NDK and GLFM: https://github.com/speedyHKjournalist/OpenMapleClient

Now I'm trying to implement https://github.com/ryantpayton/MapleStory-Client/blob/master/IO/UITypes/UINpcTalk.cpp#L245

**Comment by ryantpayton** [comment]
@speedyHKjournalist I thought you were trying to implement something new. If that's the case I don't support anything other than Windows right now. You are welcome to support this though.
