### ISSUE TITLE
sorry to bother, where can i find nx/wx files. 

### ISSUE THREAD

**Issue by zstu-jack** [ryantpayton/MapleStory-Client#9]
i have alreay install heaven ms and can login by v83 client.
but i can't edit the client source code.
so i turn to HeavenClient, but i don't know where to find all required wx files.

Thank you in advance for letting me know.
my email: 1014171514@qq.com

**Comment by aufwies** [comment]
@zstu-jack You can find it from here https://github.com/MapleStoryUnity/wzData
But it can't be converted to NX files, currently.
Good luck.

**Comment by Garbage123King** [comment]
> @zstu-jack You can find it from here https://github.com/MapleStoryUnity/wzData But it can't be converted to NX files, currently. Good luck.

please help me
where can I find these files (linux client required)
[MapPretty.nx](https://drive.google.com/file/d/1d8HJkWY6ght5OAoJGtsAjNiG2BL1wcle/view?usp=sharing) (v167 GMS Map.wz)
MapLatest.nx (Lastest GMS Map.wz)
Map001.nx (Latest GMS Map001.wz)
UI.nx (Latest GMS UI.wz)
Everything else is from v83 GMS wz files

I can find v83 wz, and use [WZ2NX](https://github.com/diamondo25/Maple.js/tree/bcae96da3c8fac2a6d9af139cd1fe72718c0dc09/tools/WZ2NX) to convert it. But how can I get v167 , or latest wz? Download Link is lost.

**Comment by ryantpayton** [comment]
@Garbage123King Are you trying to run the linux version or windows?

**Comment by speedyHKjournalist** [comment]
> i have alreay install heaven ms and can login by v83 client. but i can't edit the client source code. so i turn to HeavenClient, but i don't know where to find all required wx files.
> 
> Thank you in advance for letting me know. my email: [1014171514@qq.com](mailto:1014171514@qq.com)

Hi bro, I uploaded these nx files to mega:
https://mega.nz/file/Z8FnHQjB#j_0_Hg_GqB2-MbK6OsQd4zlVq0nmgd9OYKrE1U4_PcA
https://mega.nz/file/BhNwWRSZ#mSSV6452km6X5UHQqKdzmldqXY2UAbzVsExPHh7c9c4

**Comment by speedyHKjournalist** [comment]
> > @zstu-jack You can find it from here https://github.com/MapleStoryUnity/wzData But it can't be converted to NX files, currently. Good luck.
> 
> please help me where can I find these files (linux client required) [MapPretty.nx](https://drive.google.com/file/d/1d8HJkWY6ght5OAoJGtsAjNiG2BL1wcle/view?usp=sharing) (v167 GMS Map.wz) MapLatest.nx (Lastest GMS Map.wz) Map001.nx (Latest GMS Map001.wz) UI.nx (Latest GMS UI.wz) Everything else is from v83 GMS wz files
> 
> I can find v83 wz, and use [WZ2NX](https://github.com/diamondo25/Maple.js/tree/bcae96da3c8fac2a6d9af139cd1fe72718c0dc09/tools/WZ2NX) to convert it. But how can I get v167 , or latest wz? Download Link is lost.

Hi bro, I uploaded these nx files to mega:
https://mega.nz/file/Z8FnHQjB#j_0_Hg_GqB2-MbK6OsQd4zlVq0nmgd9OYKrE1U4_PcA
https://mega.nz/file/BhNwWRSZ#mSSV6452km6X5UHQqKdzmldqXY2UAbzVsExPHh7c9c4

**Comment by huafengguo** [comment]
Hello, the nx resource you shared is out of date. There are a total of 19 nx files in the two compressed packages, and the latest source code requires 28 nx files, so the code cannot run. Can you share your source code again? Or tell me which version is on github.

> Hi bro, I uploaded these nx files to mega: https://mega.nz/file/Z8FnHQjB#j_0_Hg_GqB2-MbK6OsQd4zlVq0nmgd9OYKrE1U4_PcA https://mega.nz/file/BhNwWRSZ#mSSV6452km6X5UHQqKdzmldqXY2UAbzVsExPHh7c9c4

**Comment by huafengguo** [comment]
> > i have alreay install heaven ms and can login by v83 client. but i can't edit the client source code. so i turn to HeavenClient, but i don't know where to find all required wx files.
> > Thank you in advance for letting me know. my email: [1014171514@qq.com](mailto:1014171514@qq.com)
> 
> Hi bro, I uploaded these nx files to mega: https://mega.nz/file/Z8FnHQjB#j_0_Hg_GqB2-MbK6OsQd4zlVq0nmgd9OYKrE1U4_PcA https://mega.nz/file/BhNwWRSZ#mSSV6452km6X5UHQqKdzmldqXY2UAbzVsExPHh7c9c4

I used your nx resources and rolled back the source code to the a3a9500 version, and it was able to run. However, there were some problems. There were no monsters on the map, so I couldn't test the battle. In addition, the mission system was basically unusable.

Can anyone provide nx resources (v228, specified in Configuration.h) that match the latest source code?

**Comment by ryantpayton** [comment]
Please see issue #13. I will be reuploading everything needed soon.
